version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    networks:
      - ecommerce
  php:
    build: ./docker/php
    volumes:
      - ./:/app
      - ./docker/php/php-dev.ini:/usr/local/etc/php/conf.d/php-dev.ini
    networks:
      - ecommerce
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - ecommerce
  redis:
    image: redis/redis-stack
    ports:
      - "8001:8001"
    volumes:
      - ./docker/redis/data:/data
    networks:
      - ecommerce

networks:
  ecommerce: