version: "3"

services:
  nginx:
    image: nginxinc/nginx-unprivileged:stable
    ports:
      - "8888:8080"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    networks:
      - ecommerce
    depends_on:
      - php
      - db
  php:
    build:
      context: ./docker/php
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ./:/app
      - ./docker/php/php-dev.ini:/usr/local/etc/php/conf.d/php-dev.ini
    networks:
      - ecommerce
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql:latest
    user: "${UID}:${GID}"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - ecommerce
  redis:
    image: redis/redis-stack
    ports:
      - "8001:8001"
    volumes:
      - ./docker/redis/data:/data
    networks:
      - ecommerce

networks:
  ecommerce: