version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    networks:
      - ecommerce
  php:
    build: ./docker/php
    volumes:
      - ./:/app
    networks:
      - ecommerce
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - ecommerce

networks:
  ecommerce: